config/routes.rb
Rails.application.routes.draw do
  get 'pages_controller/index'
  devise_for :user
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/register" => "devise/registrations#new"
    get "/logout" => "devise/sessions#destroy"
  end

  resources :articles

  get "/blog" => "blog#index"
  get "/blog/:id" => "blog#single"

  root "pages_controller#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def create
        # render plain: params[:article].inspect
        @article = Article.new(article_params)
       if @article.save
       	flash[:success] = "Post saved successfully"
        redirect_to @article
       else
        render "new"
       end
    end

    def show
        @article = Article.find(params[:id])
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
       
        if @article.update(article_params)
        	flash[:success] = "Post saved successfully"
          redirect_to @article
        else
          render 'edit'
        end
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy
       
        redirect_to articles_path
    end

    private
        def article_params
            params.require(:article).permit(:title, :text)
        end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
	def index
		@blogs = Article.all
	end
	def single
        @blog = Article.find(params[:id])
    end
end

app/controllers/pages_controller_controller.rb
class PagesControllerController < ApplicationController
  def index
  	render 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/pages_controller_helper.rb
module PagesControllerHelper
end

app/views/articles/_message.html.erb
<% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>

app/views/articles/edit.html.erb
<!-- Page Title -->
    <div class="section section-breadcrumbs">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h1>Edit Blog</h1>
          </div>
        </div>
      </div>
    </div>
        
        <div class="section">
        <div class="container">
        <div class="row">
          <div class="col-sm-8 col-md-offset-2">
            <div class="basic-login">
              
              <%= form_with(model: @article, local: true) do |form| %>
 
              <%= render 'message' %>
                
               
                <div class="form-group">
                  <%= form.label :title %><br>
                  <%= form.text_field :title, class: "form-control" %>
                </div>
               
                <div class="form-group">
                  <%= form.label :Body %><br>
                  <%= form.text_area :text , class: "form-control"%>
                </div>
               
                <div class="form-group">
                  <%= form.submit "Edit Post", :class => "btn btn-success" %>
                </div>
               
              <% end %>
               
              <%= link_to 'Back', articles_path, class: 'btn btn-primary' %>
            </div>
          </div>
          
        </div>
      </div>
    </div>

app/views/articles/index.html.erb
<div class="panel well">
  <div class="panel-heading">
    <h1>Listing articles</h1>

    <%= link_to 'New article', new_article_path, class: 'btn btn-primary' %>
  </div>
  <div class="panel-body">
     
    <table class="table table-responsive">
      <tr>
        <th>Title</th>
        <th>Text</th>
        <th colspan="3">Actions</th>
      </tr>
     
      <% @articles.each do |article| %>
        <tr>
          <td><%= article.title %></td>
          <td><%= article.text %></td>
          <td><%= link_to 'Show', article_path(article), class: 'btn btn-primary' %></td>
          <td><%= link_to 'Edit', edit_article_path(article), class: 'btn btn-warning' %></td>
          <td><%= link_to 'Destroy', article_path(article), class: 'btn btn-danger',
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </table>
  </div>

</div>

app/views/articles/new.html.erb
<!-- Page Title -->
    <div class="section section-breadcrumbs">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h1>New Blog</h1>
          </div>
        </div>
      </div>
    </div>
        
        <div class="section">
        <div class="container">
        <div class="row">
          <div class="col-sm-8 col-md-offset-2">
            <div class="basic-login">
              
              <%= form_with scope: :article, url: articles_path, local: true do |form| %>
               
                <%= render 'message' %>
               
                <div class="form-group">
                  <%= form.label :title %><br>
                  <%= form.text_field :title, class: "form-control" %>
                </div>
               
                <div class="form-group">
                  <%= form.label :Body %><br>
                  <%= form.text_area :text , class: "form-control"%>
                </div>
               
                <div class="form-group">
                  <%= form.submit "Create Post", :class => "btn btn-success" %>
                </div>
               
              <% end %>
               
              <%= link_to 'Back', articles_path, class: 'btn btn-primary' %>
            </div>
          </div>
          
        </div>
      </div>
    </div>

app/views/articles/show.html.erb
  <div class="section section-breadcrumbs">
      <div class="container">
        <div class="row">
          <%= render 'message' %>
          <div class="col-md-12">
            <h1> <%= @article.title %></h1>
            <h5 style="color: #fff;"> <%= @article.created_at.strftime("%d %m %Y") %></h5>
          </div>
        </div>
      </div>
    </div>
  <div class="well panel">
    <p class="panel-heading">
      <strong>Title:</strong>
      <%= @article.title %>
    </p>
     
    <p class="panel-body">
      <strong>Text:</strong>
      <%= @article.text %>
    </p>
 
  <div class="panel-footer">
    <%= link_to 'Edit', edit_article_path(@article) , class: 'btn btn-warning'%> |
    <%= link_to 'Back', articles_path, class: 'btn btn-info' %>
  </div> 
</div>

app/views/blog/index.html.erb
<!-- Page Title -->
		<div class="section section-breadcrumbs">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h1>Blog Posts</h1>
					</div>
				</div>
			</div>
		</div>
        
        <!-- Posts List -->
        <div class="section blog-posts-wrapper">
	    	<div class="container">
				<div class="row">
					<!-- Post -->
				<% @blogs.each do |blog| %>
					<div class="col-md-4 col-sm-6">
						<div class="blog-post">
							<div class="post-info">
								<div class="post-date">
									<div class="date"><%= @blog %></div>
								</div>
								<div class="post-comments-count">
									<a href="page-blog-post-right-sidebar.html" title="Show Comments"><i class="glyphicon glyphicon-comment icon-white"></i>57</a>
								</div>
							</div>
							<a href="/blog/<%= blog.id %>"><img src="/img/blog3.jpg" class="post-image" alt="Post Title"></a>
							<div class="post-title">
								<h3><a href="/blog/<%= blog.id %>"><%= blog.title %></a></h3>
							</div>
							<div class="post-summary">
								<p><%=  truncate(blog.text, :length => 400, :omission => '... (continued)') %> </p>
							</div>
							<div class="post-more">
								<a href="/blog/<%= blog.id %>" class="btn btn-small">Read More</a>
							</div>
						</div>
					</div>
				<% end %>

				</div>
			</div>
	    </div>
	    <!-- End Posts List -->

app/views/blog/single.html.erb
<!-- Page Title -->
		<div class="section section-breadcrumbs">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h1>Blog Post (Sidebar Right)</h1>
					</div>
				</div>
			</div>
		</div>
        
        <div class="section">
	    	<div class="container">
				<div class="row">
					<!-- Blog Post -->
					<div class="col-sm-8">
						<div class="blog-post blog-single-post">
							<div class="single-post-title">
								<h3><%=  @blog.title %></h3>
							</div>
							<div class="single-post-info">
								<i class="glyphicon glyphicon-time"></i>30 JAN, 2013 <a href="#" title="Show Comments"><i class="glyphicon glyphicon-comment"></i>11</a>
							</div>
							<div class="single-post-image">
								<img src="/img/blog-large.jpg" alt="Post Title">
							</div>
							<div class="single-post-content">
								<%= @blog.text %>
							</div>
							<!-- Comments -->
							<div class="post-coments">
								<h4>Comments (53)</h4>
								<ul class="post-comments">
									<li>
										<div class="comment-wrapper">
											<div class="comment-author"><img src="/img/user1.jpg" alt="User Name"> User Name</div>
											<p>
												Morbi eleifend congue elit nec sagittis. Praesent aliquam lobortis tellus, nec consequat massa ornare vitae. Ut fermentum justo vel venenatis eleifend. Fusce id magna eros. Interdum et malesuada fames ac ante ipsum primis in faucibus.
											</p>
											<!-- Comment Controls -->
											<div class="comment-actions">
												<span class="comment-date">June 10th, 2013 3:16 pm</span>
												<a href="#" data-toggle="tooltip" data-original-title="Vote Up" class="show-tooltip"><i class="glyphicon glyphicon-thumbs-up"></i></a>
												<a href="#" data-toggle="tooltip" data-original-title="Vote Down" class="show-tooltip"><i class="glyphicon glyphicon-thumbs-down"></i></a>
												<span class="label label-success">+8</span>
												<a href="#" class="btn btn-micro btn-grey comment-reply-btn"><i class="glyphicon glyphicon-share-alt"></i> Reply</a>
											</div>
										</div>
									</li>
									<li>
										<ul>
											<li>
												<div class="comment-wrapper">
													<div class="comment-author"><img src="/img/user2.jpg" alt="User Name"> User Name</div>
													<p>
														Vivamus euismod elit ac libero facilisis tristique. Duis mollis non ligula vel tincidunt. Nulla consectetur libero id nunc ornare, vel vulputate tellus mollis. Sed quis nulla magna.
													</p>
													<!-- Comment Controls -->
													<div class="comment-actions">
														<span class="comment-date">June 10th, 2013 3:16 pm</span>
														<a href="#" data-toggle="tooltip" data-original-title="Vote Up" class="show-tooltip"><i class="glyphicon glyphicon-thumbs-up"></i></a>
														<a href="#" data-toggle="tooltip" data-original-title="Vote Down" class="show-tooltip"><i class="glyphicon glyphicon-thumbs-down"></i></a>
														<span class="label label-danger">-2</span>
														<a href="#" class="btn btn-micro btn-grey comment-reply-btn"><i class="glyphicon glyphicon-share-alt"></i> Reply</a>
													</div>
												</div>
											</li>
										</ul>
									</li>
									<li>
										<div class="comment-wrapper">
											<div class="comment-author"><img src="/img/user5.jpg" alt="User Name"> User Name</div>
											<p>
												Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel magna lectus.
											</p>
											<!-- Comment Controls -->
											<div class="comment-actions">
												<span class="comment-date">June 10th, 2013 3:16 pm</span>
												<a href="#" data-toggle="tooltip" data-original-title="Vote Up" class="show-tooltip"><i class="glyphicon glyphicon-thumbs-up"></i></a>
												<a href="#" data-toggle="tooltip" data-original-title="Vote Down" class="show-tooltip"><i class="glyphicon glyphicon-thumbs-down"></i></a>
												<span class="label label-success">+8</span>
												<a href="#" class="btn btn-micro btn-grey comment-reply-btn"><i class="glyphicon glyphicon-share-alt"></i> Reply</a>
											</div>
										</div>
									</li>
								</ul>
								<!-- Pagination -->
								<div class="pagination-wrapper ">
									<ul class="pagination pagination-sm">
										<li class="disabled"><a href="#">Previous</a></li>
										<li class="active"><a href="#">1</a></li>
										<li><a href="#">2</a></li>
										<li><a href="#">3</a></li>
										<li><a href="#">4</a></li>
										<li><a href="#">5</a></li>
										<li><a href="#">Next</a></li>
									</ul>
								</div>
								<!-- Comments Form -->
								<h4>Leave a Comment</h4>
								<div class="comment-form-wrapper">
									<form class="">
				        				<div class="form-group">
				        				 	<label for="comment-name"><i class="glyphicon glyphicon-user"></i> <b>Your name</b></label>
											<input class="form-control" id="comment-name" type="text" placeholder="">
										</div>
										<div class="form-group">
											<label for="comment-email"><i class="glyphicon glyphicon-envelope"></i> <b>Your Email</b></label>
											<input class="form-control" id="comment-email" type="text" placeholder="">
										</div>
										<div class="form-group">
											<label for="comment-message"><i class="glyphicon glyphicon-comment"></i> <b>Your Message</b></label>
											<textarea class="form-control" rows="5" id="comment-message"></textarea>
										</div>
										<div class="form-group">
											<button type="submit" class="btn btn-large pull-right">Send</button>
										</div>
										<div class="clearfix"></div>
				        			</form>
								</div>
								<!-- End Comment Form -->
							</div>
							<!-- End Comments -->
						</div>
					</div>
					<!-- End Blog Post -->
					<!-- Sidebar -->
					<div class="col-sm-4 blog-sidebar">
						<h4>Search our Blog</h4>
						<form>
							<div class="input-group">
								<input class="form-control input-md" id="appendedInputButtons" type="text">
								<span class="input-group-btn">
									<button class="btn btn-md" type="button">Search</button>
								</span>
							</div>
						</form>
						<h4>Recent Posts</h4>
						<ul class="recent-posts">
							<li><a href="#">Lorem ipsum dolor sit amet</a></li>
							<li><a href="#">Sed sit amet metus sit</a></li>
							<li><a href="#">Nunc et diam volutpat tellus ultrices</a></li>
							<li><a href="#">Quisque sollicitudin cursus felis</a></li>
						</ul>
						<h4>Categories</h4>
						<ul class="blog-categories">
							<li><a href="#">Lorem ipsum</a></li>
							<li><a href="#">Sed sit amet metus</a></li>
							<li><a href="#">Nunc et diam </a></li>
							<li><a href="#">Quisque</a></li>
						</ul>
						<h4>Archive</h4>
						<ul>
							<li><a href="#">January 2013</a></li>
							<li><a href="#">February 2013</a></li>
							<li><a href="#">March 2013</a></li>
							<li><a href="#">April 2013</a></li>
							<li><a href="#">May 2013</a></li>
						</ul>
					</div>
					<!-- End Sidebar -->
				</div>
			</div>
	    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Test App</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">

        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <link rel="stylesheet" href="/css/bootstrap.min.css">
        <link rel="stylesheet" href="/css/icomoon-social.css">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,600,800' rel='stylesheet' type='text/css'>

        <link rel="stylesheet" href="/css/leaflet.css" />
    <!--[if lte IE 8]>
        <link rel="stylesheet" href="/css/leaflet.ie.css" />
    <![endif]-->
    <link rel="stylesheet" href="/css/main.css">

        <script src="/js/modernizr-2.6.2-respond-1.1.0.min.js"></script>
    </head>
    <body>
        <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->
        

        <!-- Navigation & Logo-->
        <div class="mainmenu-wrapper">
          <div class="container">
            <div class="menuextras">
          <div class="extras">
            <ul>
              <!-- <li class="shopping-cart-items"><i class="glyphicon glyphicon-shopping-cart icon-white"></i> <a href="#"><b>3 items</b></a></li>
              <li>
                <div class="dropdown choose-country">
                  <a class="#" data-toggle="dropdown" href="#"><img src="/img/flags/gb.png" alt="Great Britain"> UK</a>
                  <ul class="dropdown-menu" role="menu">
                    <li role="menuitem"><a href="#"><img src="/img/flags/us.png" alt="United States"> US</a></li>
                    <li role="menuitem"><a href="#"><img src="/img/flags/de.png" alt="Germany"> DE</a></li>
                    <li role="menuitem"><a href="#"><img src="/img/flags/es.png" alt="Spain"> ES</a></li>
                  </ul>
                </div>
              </li> -->
              <% if user_signed_in? %>
          
                  <li>
                    <div class="dropdown choose-country">
                      <a class="#" data-toggle="dropdown" href="#"><%= current_user.email %></a>
                      <ul class="dropdown-menu" role="menu">
                        <li role="menuitem"><a href="/logout"> Logout</a></li>
                        <li role="menuitem"><a href="/articles"> Blog</a></li>

                      </ul>
                    </div>
                  </li>
                <%else%>
                  <li><a href="/login">Login</a></li>
                <% end %>
              </ul>

          </div>
            </div>
            <nav id="mainmenu" class="mainmenu">
          <ul>
            <li class="logo-wrapper"><a href="/"><img src="/img/mPurpose-logo.png" alt="Multipurpose Twitter Bootstrap Template"></a></li>
            <li>
              <a href="/">Home</a>
            </li>
            <li>
              <a href="#">Features</a>
            </li>
            
            <li>
              <a href="#">Credits</a>
            </li>
          </ul>
        </nav>
      </div>
    </div>

       <%= yield %>

      <!-- Footer -->
      <div class="footer">
        <div class="container">
          <div class="row">
            <div class="col-footer col-md-3 col-xs-6">
              <h3>Our Latest Work</h3>
              <div class="portfolio-item">
              <div class="portfolio-image">
                <a href="page-portfolio-item.html"><img src="/img/portfolio6.jpg" alt="Project Name"></a>
              </div>
            </div>
            </div>
            <div class="col-footer col-md-3 col-xs-6">
              <h3>Navigate</h3>
              <ul class="no-list-style footer-navigate-section">
                <li><a href="page-blog-posts.html">Blog</a></li>
                <li><a href="page-portfolio-3-columns-2.html">Portfolio</a></li>
                <li><a href="page-products-3-columns.html">eShop</a></li>
                <li><a href="page-services-3-columns.html">Services</a></li>
                <li><a href="page-pricing.html">Pricing</a></li>
                <li><a href="page-faq.html">FAQ</a></li>
              </ul>
            </div>
            
            <div class="col-footer col-md-4 col-xs-6">
              <h3>Contacts</h3>
              <p class="contact-us-details">
                  <b>Address:</b> 123 Fake Street, LN1 2ST, London, United Kingdom<br/>
                  <b>Phone:</b> +44 123 654321<br/>
                  <b>Fax:</b> +44 123 654321<br/>
                  <b>Email:</b> <a href="mailto:getintoutch@yourcompanydomain.com">getintoutch@yourcompanydomain.com</a>
                </p>
            </div>
            <div class="col-footer col-md-2 col-xs-6">
              <h3>Stay Connected</h3>
              <ul class="footer-stay-connected no-list-style">
                <li><a href="#" class="facebook"></a></li>
                <li><a href="#" class="twitter"></a></li>
                <li><a href="#" class="googleplus"></a></li>
              </ul>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="footer-copyright">&copy; 2013 mPurpose. All rights reserved.</div>
            </div>
          </div>
        </div>
      </div>

        <!-- Javascripts -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="/js/jquery-1.9.1.min.js"><\/script>')</script>
        <script src="/js/bootstrap.min.js"></script>
        <script src="http://cdn.leafletjs.com/leaflet-0.5.1/leaflet.js"></script>
        <script src="/js/jquery.fitvids.js"></script>
        <script src="/js/jquery.sequence-min.js"></script>
        <script src="/js/jquery.bxslider.js"></script>
        <script src="/js/main-menu.js"></script>
        <script src="/js/template.js"></script>

    </body>
</html>